Link partially qualified identifiers when documenting single module
mitmproxy/pdoc pull request #544
Opened 2023-05-13 14:27 UTC by Crozzers

Currently, to link to another identifier using pdoc, the item in question must either be part of the current file or you must give the fully qualified name, including the module name.

This is very inconvenient when documenting a single module with a long name. For example:
```python
# my_long_module_name/__init__.py
from .helpers import something

def a():
     '''This will not be linked: `helpers.something`'''
    pass

def b():
     '''This will be linked: `my_long_module_name.helpers.something`'''
    pass

# my_long_module_name/helpers.py
def something():
    pass
```

This PR changes the `possible_sources` function in `render_helpers.py` to check if every module name in `all_modules` starts with the same top-level package name. For example, the following list shares the top-level module name of `my_long_module_name`:
```
my_long_module_name
my_long_module_name.helpers
my_long_module_name.types
my_long_module_name.types.abc
```
If a common, global package name can be identified and the `identifier` does not start with this package name, the package name is prefixed to the identifier.
This means that `helpers.something` from earlier will become `my_long_module_name.helpers.something`, allowing the `a()` function to have the intended link put in.

This does change how some existing code is rendered. The `demopackage._child_c.C` docstring in the `demopackage` test used to say `...inherits from .child_b.B` but now will be auto-linked as `...inherits from .<a href="#B">demopackage.B</a>`.
This docstring doesn't contain any links so it seems like a bug that it's being linkified in the first place, but I'd like to know your thoughts.

2023-05-14 11:58 UTC, Crozzers commented
> This docstring doesn't contain any links so it seems like a bug that it's being linkified in the first place, but I'd like to know your thoughts.

Regarding this, I created a new branch from main and modified a docstring in the `demopackage.child_c` submodule in this commit: https://github.com/Crozzers/pdoc/commit/6f01c475dce5eaf15d8909cd9c44bb2692bb42d1

Here is the new docstring:
```python
# test/testdata/demopackage/child_c.py
class C(child_b.B):
    """This class is defined in .child_c and inherits from .child_b.B

    Here's an identifier that isn't enclosed in back ticks: demopackage.child_b.B
    """

    def c(self):
        return 2
```

And this is what pdoc generated:
![image](https://github.com/mitmproxy/pdoc/assets/57498990/43138a1c-79e4-4d4d-8d53-8f098afc9d72)

From what I can see, linkify is being called from a macro in the `module.html.jinja2` template, but I haven't narrowed it down any further.

I'm not sure if this is intentional behaviour, since the [pdoc API docs](https://pdoc.dev/docs/pdoc.html#link-to-other-identifiers) state that you can enclose references in backticks, not that you must. However, it is certainly unexpected

2023-06-20 06:34 UTC, mhils requested changes
Thank you for the PR and sorry for letting it sit so long! 🙈 
Honestly I'm not a big fan of this change - I feel this muddies the waters on what an absolute and what a relative identifier is. I really appreciate your work on markdown2 though, so I'd like to accomodate your use case if somehow possible. 

As an alternative, how would you feel about making relative links start with `.` or `..`? For example, you'd write ```Do `.helpers.something` with a `.types.BigThing`.```. That'd be a bit more complex to implement, but at least it's not ambiguous.

2023-06-20 06:34 UTC, mhils commented on pdoc/render_helpers.py
> +    if len(set(s.partition(".")[0] for s in all_modules)) == 1:
This here is https://accidentallyquadratic.tumblr.com/ behavior (number of modules * number of identifiers/function calls) I think?

2023-06-24 10:28 UTC, Crozzers commented on pdoc/render_helpers.py
> +    if len(set(s.partition(".")[0] for s in all_modules)) == 1:
Not sure. Depends on how `str.partition` behaves with longer strings I guess.
I've changed it in the most recent revision to use `str.startswith` and loop over `all_modules` which I think should be fine

2023-06-24 10:38 UTC, Crozzers commented
> Thank you for the PR and sorry for letting it sit so long

No worries! Apologies for the delay in getting back to you.

> As an alternative, how would you feel about making relative links start with . or ..? For example, you'd write Do `.helpers.something` with a `.types.BigThing`.

Yep, that makes alot more sense actually. I've updated the branch to only link partially qualified names if the name is prefixed with `.` and if all possible sources are within the same module.

2023-07-24 09:56 UTC, mhils commented
Thanks for keeping this up-to-date. I don't have the capacity to review this thoroughly at the moment, but I will get back to this once I have a bit of time for pdoc again. :)

2023-09-06 09:58 UTC, mhils commented
Thanks for waiting so patiently! I've now had a chance to look at the implementation more closely and tweak some things. Let me know if that looks good from your end, and I'll be happy to merge things and ship a pdoc release right after. 😃

2023-09-06 10:30 UTC, mhils commented on pdoc/render_helpers.py
> +    if len(set(s.partition(".")[0] for s in all_modules)) == 1:
I'm assuming `str.partition` to be O(1) here. `all_modules` grows linearly with the number of modules. The number of docstrings also grows ~linearly with the number of modules. Each docstring needs on average X calls to `possible_sources` (where X is some constant):
```python
for module in all_modules:
     # X calls to possible_sources
     if len(set(s.partition(".")[0] for s in all_modules)) == 1:
```

2023-09-06 18:05 UTC, Crozzers commented
Is the intention to only do relative links if the link starts with `..`? Or is `..` used to resolve a parent module?

There are a few instances in the `demopackage` where single dot refs are made but no link occurs. For example, in [`demopackage.child_c`](https://github.com/Crozzers/pdoc/blob/8c20cae0988a44a324fb46a12b7fe60b976c8ae9/test/testdata/demopackage/child_c.py#L6) it says:
```
This class is defined in .child_c and inherits from .child_b.B
```
But no links are made.
![image](https://github.com/mitmproxy/pdoc/assets/57498990/4356a8c2-48fd-4cd3-a584-6903e0a7b14c)


Debugging this, when the code gets to `linkify_repl`, the `mod.modulename` is `'demopackage.child_c'` which results in an identifier of `'demopackage.child_c.child_b.B'`.

It seems that `.` is referring to items in the same module, though I assumed it would refer to adjacent submodules

2023-09-06 18:08 UTC, mhils commented
> Is the intention to only do relative links if the link starts with `..`? Or is `..` used to resolve a parent module?

If we are in module `foo.bar.baz` and see a link to `.qux.Quux`, that should refer to `foo.bar.qux.Quux`. `..qux.Quux` should refer to `foo.qux.Quux`. So `..` is used to resolve the parent module.

I'll look into the issues you mentioned momentarily. :)

2023-09-06 18:45 UTC, mhils commented
Thanks! Your review caught an importan bug, I was testing from `__init__.py` only, where `.foo` should refer to a child and not an adjacent module (matching how imports work).

Looking better now?

2023-09-08 13:20 UTC, mhils approved these changes

2023-09-09 10:52 UTC, Crozzers commented
Hi, apologies for slow reply.

I found another issue, where imported classes with relative docstrings don't link properly in the module that imports them. EG:
![image](https://github.com/mitmproxy/pdoc/assets/57498990/671a3120-3a30-4f16-b97f-f7abd684eb1a)
Here, the `parent_module` is set as `demopackage.subpackage`, so it cannot find `.child_b` within that module.

Currently trying to figure out if there's a way to tell what member the current docstring belongs to so that the parent module can be properly adjusted.

2023-09-09 21:25 UTC, mhils commented
Thanks for the thorough testing! This is a really useful collaboration. 🍰 
I've just pushed for the issue in your last comment + some nits. Let me know how that looks to you, and no worries on (not even) slow replies! 😊

2023-09-10 08:58 UTC, Crozzers commented
All the links in `demopackage` seem to be linking to all the right places. Looks good to me! Thank you so much for your help on this one

2023-09-10 09:50 UTC, merged